title: <p align="center"> Prithviraj Patil </p>
logo: /assets/img/logo_1.png
description: Over 10 Years of Experience, enthusiastic in solving real-world problems. Efficient Python,SQL,Tableau,GIT,Database Admin,Oracle Single-Sign Governance 

theme: jekyll-theme-minimal
